### ISSUE TITLE
pause / resume timer

### ISSUE THREAD

**Issue by mef** [d3/d3-timer#14]
In addition to the stop method, it would be useful to be able to pause and resume a timer.

Do you think that these functions would fit inside d3-timer?

**Comment by mbostock** [comment]
How would pause and resume be different from the existing stop and restart?

**Comment by mef** [comment]
This would simplify the use of `d3.timeout` with a delay:

When calling `pause`, d3.timer would manage the remaining time internally, so that when calling resume, the timer would be restarted in a transparent way

````javascript
// callback will be executed in 2000 ms
var t = d3.timeout(callback, 2000)

// ...

// something triggers a pause (e.g. user clicking on "pause" button) before delay is elapsed
t.pause()

// ...

// another event triggers the resume
t.pause()

// callback will be executed in xx remaining ms, I didn't have to calculate the remaining delay.

````

Does this make sense?

**Comment by mbostock** [comment]
Okay, I see. So it’s like stopping the timer and then restarting it, but
the timer tracks the duration it was paused to set the new delay
automatically, as if you froze time just for that timer.

What’s the use case, though? Why do you want this feature? It doesn’t sound
too hard to implement this using stop and restart.

**Comment by mef** [comment]
>  What’s the use case, though? Why do you want this feature?

I'm updating a sequencer: the module schedule some actions, and sometimes the user needs to suspend the upcoming events for some unspecified duration. Current implementation users setTimeout / clearTimeout, I'm rewriting it for more precision.

> It doesn’t sound too hard to implement this using stop and restart.

Yes, not a big deal. I just thought the feature did fit inside d3-timer.

**Comment by mbostock** [comment]
I’m not planning on implementing this, but thank you for the suggestion. If you implement it and discover that it’s super-useful then let me know.

**Comment by mef** [comment]
No worry.

Thanks for your time :)

**Comment by woodev01** [comment]
I have created a Pausable timer, which will allow you to Pause/Resume your timer.

@mbostock - I have a pull request pending, if you'd like to see the implementation, otherwise:

@mef - You can use my fork of d3-timer, which has the PausableTimer implemented
