### ISSUE TITLE
Example that uses d3

### ISSUE THREAD

**Issue by steveharoz** [d3/d3-timer#19]
[This block](https://bl.ocks.org/mbostock/157333662ef11c151080) is a popular example for d3.timer. However, it uses embedded code that isn't 100% compatible with the library. 

I've updated a fork of the example [here](https://bl.ocks.org/steveharoz/4da6c64f5f0af68ddb0110ef67d02a66) to use the actual library.

(I realize that I'm filing a bug for a seemingly unrelated gist, but it's the defacto example for this library)

**Comment by mbostock** [comment]
Sure, that was an old version of the library. I’ve updated it. The perils of having so many examples…
