### ISSUE TITLE
"Invalid calling object" in Edge browser.

### ISSUE THREAD

**Issue by KonradKlimczak** [d3/d3-timer#22]
Hello,

I use victory library (for generating chart based on d3.js) and on unmounting process it uses `timer.now()`, which causes _(sometimes)_ "**Invalid calling object**". From what I read it's connected with passing references to native functions.
I imagine that this is the problem:
`setFrame = typeof requestAnimationFrame === "function" ? requestAnimationFrame : function(f) { setTimeout(f, 17); };`

In my case calling `setFrame(clearNow)` results in "**Invalid calling object**",
but calling `requestAnimationFrame(clearNow)` **works** just **fine**.

Similar problem was described here:
[https://stackoverflow.com/questions/1007340/javascript-function-aliasing-doesnt-seem-to-work](https://stackoverflow.com/questions/1007340/javascript-function-aliasing-doesnt-seem-to-work)

Regards,
Konrad

**Comment by mbostock** [comment]
Fixed in #23.
