### ISSUE TITLE
Doighlight another **d3.interval**:

### ISSUE THREAD

**Issue by Herst** [d3/d3-timer#25]
The current description of **d3.interval**:

> Like timer, except the callback is invoked only every delay milliseconds; if delay is not specified, this is equivalent to timer. A suitable replacement for setInterval that is guaranteed to not run in the background. The callback is passed the elapsed time.

It might be also worth adding that unlike `setInterval` it is also not trying to catch up, which depending on the use good case might be a good thing or not (in my experience it's always better this way and relying on the catch-up behavior is IMHO likely a sign of a suboptimal approach).

**Comment by mbostock** [comment]
I’m not sure what you mean by “trying to catch up.” A d3.interval fires at integer multiples of the specified *delay* (ignoring when time is frozen in the background; see [d3.timer](https://github.com/d3/d3-timer/blob/master/README.md#timer)). I believe in that regard it should be the same as setInterval, as opposed to calling setTimeout within a timer callback, which can cause drift.

**Comment by Herst** [comment]
I intended to create an little demo to show you what I meant: https://bl.ocks.org/Herst/f40207373c9f983cfba2e79442b51129
If you switch to `setInterval` there and then activate the slow-down for some seconds and then you turn it off you will see the counter quickly increasing because `setInterval` is trying to catch-up on the missed function calls which is why after the slowdown ended you will see it rapid-fire.

`d3.timer` is doing the right thing, just thought it might be worth noting.
