### ISSUE TITLE
when transitions are triggered in inactive tabs they accumulate and can cause page freeze

### ISSUE THREAD

**Issue by guykr** [d3/d3-timer#34]
### A little background: 
The app I'm working is used for monitoring. A common use case is to have a tab open for days.
I noticed that when a tab containing a d3 component becomes active again after a long time being inactive it causes the page to freeze.

I've managed to create a minimal test case demonstrating this: https://bl.ocks.org/guykr/5072b773cd67e6b0bff61dc00d6418f1

### A note about why it's implemented this way: 
I hijack the native `requestAnimationFrame` and simulate the tab being inactive to speed up the manifestation of this issue (Since the browser also throttles `setInterval` calls), but this can be reproduces without these measures by setting up a `setInterval` loop that schedules transitions, switching to another tab and then waiting for ~1 hour or so.

I'm aware the test case is extreme, but this happens in our app with much slower updates (and longer inactive periods)

Any ideas how this can be mitigated?

Thanks,
Guy

*not sure if this should go to d3-transition or here, but it seems related to #17

**Comment by mbostock** [comment]
Don’t use setInterval to schedule your animations; use [d3.interval](https://github.com/d3/d3-timer/blob/master/README.md#interval) instead, which will avoid scheduling the animations when the tab is backgrounded.
