### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by hustcc** [d3/d3-timer#49]
> code below

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>d3-timer memory leak</title>

  <script src="https://cdn.jsdelivr.net/npm/d3-timer@3"></script>
  <script>
    const t = d3.timer((elapsed) => {
      // run your code
    }, 150);
  </script>

<body>
</body>
</html>
```

- start in the browser

![image](https://user-images.githubusercontent.com/7856674/122211172-04e0d280-ced9-11eb-98ed-ed582b560482.png)

- after 5 min

![image](https://user-images.githubusercontent.com/7856674/122211127-f692b680-ced8-11eb-8554-6b5d54e1b371.png)

**Comment by jzombie** [comment]
@hustcc  I'm starting to use this timer in some of my projects and saw this issue. 

I'm using the test script you provided and the memory footprint goes back down after about a minute or so, goes back up, then back down.
